export { composeGroundedPrompt } from "./compose";
export {
  ADDRESS_FORMS,
  COMPOSE_FAILURE_CODES,
  COMPOSE_SEND_CONTROLS,
  EVIDENCE_ASSERTION_KINDS,
  STYLE_FORMALITY_LEVELS,
  STYLE_PRECEDENCE,
} from "./types";
export type {
  AddressForm,
  CampaignStyleOverride,
  CampaignOverrideGroundingProvenance,
  ComposeBaseSourceVersions,
  ComposeFailureCode,
  ComposeFailureReason,
  CompositionProvenance,
  CompositionHook,
  CompositionEvidence,
  ComposePromptInput,
  ComposePromptResult,
  ComposeSendControls,
  ComposedPrompt,
  ExplicitStyleLayer,
  EvidenceAssertion,
  EvidenceAssertionKind,
  FailedPrompt,
  FreelancerProfileFacts,
  GroundedFact,
  InferredStyleLayer,
  ProspectGrounding,
  ProspectContextSnapshot,
  ResolvedStyle,
  ResolvedStyleField,
  StoppedPrompt,
  StylePrecedenceSource,
  StyleFormality,
  StyleStepOverride,
  VersionedAcceptedInferredStyleLayer,
  VersionedCampaignStyleOverride,
  VersionedCampaignSource,
  VersionedExplicitStyleLayer,
  VersionedFreelancerProfile,
} from "./types";
export type { PromptOverrideVersionRef } from "@relanmo/domain/contracts";

export const promptCompositionSurface = "ENABLED" as const;
